---
abstract: 'RT-Extension-GWSImport Extension'
author:
  - 'Bradley Bell <bradleyb@uw.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-GWSImport
no_index:
  directory:
    - inc
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/uw-it-cte/rt-extension-gwsimport
version: 0.01
x_module_install_rtx_version: 0.40
x_requires_rt: 4.2.0
x_rt_too_new: 4.6.0
